# does not depend on files(except crimemapdb_dump.sql), all images are downloaded from docker hub
services:
  database:
    image: postgis/postgis:16-3.5
    container_name: crime_map_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crimemapdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./crimemapdb_dump.sql:/docker-entrypoint-initdb.d/crimemapdb_dump.sql
    ports:
      - "5432:5432"

  api:
    image: turbo821/miphi-crime-mapping-api:01-18.2
    container_name: crime_map_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ALLOWED_ORIGINS=http://localhost:3000,https://localhost:3000
      - CONNECTION_STRING=Host=database;Port=5432;Database=crimemapdb;Username=postgres;Password=postgres
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "8081:8081"
     
  client:
    image: turbo821/miphi-crime-mapping-client:01-18
    container_name: crime_map_client
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api
    ports:
      - "3000:3000"
