services:
  database:
    image: postgres:16
    container_name: crime_map_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crimemapdb
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./backend
      dockerfile: Web/Dockerfile
    container_name: crime_map_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ALLOWED_ORIGINS=http://localhost:3000
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=crimemapdb;Username=postgres;Password=postgres
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "8081:8081"
     
  client:
    build:
      context: ./frontend
      dockerfile: miphi-crime-mapping-client/Dockerfile
    container_name: crime_map_client
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/crime-marks
    depends_on:
      - api
    ports:
      - "3000:3000"
